@startuml use_cases
left to right direction
skinparam packageStyle rectangle

actor "User" as user

rectangle "Person Management System" {
    usecase "UC-001\Search People" as UC001
    usecase "UC-002\nManage Person" as UC002
    usecase "UC-003\nDelete Person" as UC003
}

user --> UC001
user --> UC002
user --> UC003

@enduml
